function device = linear_device_data_type()
device.class        = [];
device.R            = [];
device.sigma        = [];
device.L            = [];
device.C            = [];
device.R_is_dummy   = [];
device.L_is_dummy   = [];
device.C_is_dummy   = [];