function node_info = node_info_type()
node_info.names      = {};
node_info.pos        = [];
node_info.is_trans   = [];
node_info.disp_only  = [];
node_info.floating   = [];
node_info.Cgrd       = [];
node_info.id         = [];
node_info.active     = false;
node_info.C          = [];
node_info.timeconstant = [];